name: Prettifying

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "publication/**"
      - "errata.html"
      - "errata11.html"
      - "ontology/*.html"
      - "validation/tm-json-schema-validation.json"
      - "context/td-context-1.1.jsonld"
      - "visualization/*.png"
      - "visualization/*.svg"

permissions:
  contents: write

jobs:
  prettier:
    name: Check coding style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Nerixyz/actionsx-prettier@v3-adj
        with:
          args: --check .